# Generated by Django 5.2.11 on 2026-03-02 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokuman', '0002_anlamadimkaydi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatSheetExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('md', 'Markdown'), ('pdf', 'PDF'), ('docx', 'DOCX')], default='md', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('dosya', models.FileField(blank=True, null=True, upload_to='exports/cheatsheet/')),
                ('hata', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dokuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='dokuman.dokuman')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheatsheet_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='exporter_ch_created_6c3faa_idx'), models.Index(fields=['status'], name='exporter_ch_status_5def0a_idx'), models.Index(fields=['format'], name='exporter_ch_format_85f8f4_idx')],
            },
        ),
    ]
