# Generated by Django 5.2.11 on 2026-02-28 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=255)),
                ('dosya', models.FileField(upload_to='dokuman_asistani/')),
                ('mime', models.CharField(blank=True, max_length=128)),
                ('durum', models.CharField(default='yuklendi', max_length=32)),
                ('hata', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumanlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveIntegerField(default=0)),
                ('tur', models.CharField(default='paragraf', max_length=32)),
                ('metin', models.TextField()),
                ('adres', models.CharField(max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('zorluk_skoru', models.FloatField(default=0.0)),
                ('zorluk', models.CharField(default='kolay', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dokuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcalar', to='dokuman.dokuman')),
            ],
        ),
        migrations.CreateModel(
            name='Not',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokuman_notlari', to=settings.AUTH_USER_MODEL)),
                ('parca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='dokuman.parca')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(default='teknoloji', max_length=32)),
                ('stil', models.CharField(default='kanka', max_length=32)),
                ('seviye', models.CharField(default='baslangic', max_length=16)),
                ('detay', models.PositiveIntegerField(default=60)),
                ('ornek', models.PositiveIntegerField(default=70)),
                ('mizah', models.PositiveIntegerField(default=40)),
                ('sinav_modu', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dokuman_profili', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='parca',
            index=models.Index(fields=['dokuman', 'sira'], name='dokuman_par_dokuman_9b6fea_idx'),
        ),
        migrations.AddIndex(
            model_name='parca',
            index=models.Index(fields=['dokuman', 'zorluk'], name='dokuman_par_dokuman_d6993b_idx'),
        ),
    ]
