# Generated by Django 5.2.11 on 2026-03-02 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokuman', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnlamadimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaynak_tipi', models.CharField(choices=[('highlight', 'Highlight'), ('chunk', 'Chunk'), ('serbest', 'Serbest')], default='serbest', max_length=16)),
                ('kaynak_id', models.BigIntegerField(blank=True, null=True)),
                ('secim_metni', models.TextField(blank=True, default='')),
                ('notlar', models.TextField(blank=True, default='')),
                ('sayfa_no', models.IntegerField(blank=True, null=True)),
                ('baslangic_char', models.IntegerField(blank=True, null=True)),
                ('bitis_char', models.IntegerField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('acik', 'Açık'), ('cozuldu', 'Çözüldü')], default='acik', max_length=16)),
                ('cozum_notu', models.TextField(blank=True, default='')),
                ('cozulme_zamani', models.DateTimeField(blank=True, null=True)),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
                ('dokuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anlamadim_kayitlari', to='dokuman.dokuman')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anlamadim_kayitlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-olusturuldu'],
                'indexes': [models.Index(fields=['kullanici', 'durum'], name='dokuman_anl_kullani_35c897_idx'), models.Index(fields=['dokuman', 'durum'], name='dokuman_anl_dokuman_3f2d70_idx'), models.Index(fields=['kaynak_tipi', 'kaynak_id'], name='dokuman_anl_kaynak__3336d9_idx')],
            },
        ),
    ]
