# Generated by Django 5.2.11 on 2026-03-03 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokuman', '0002_anlamadimkaydi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciTercih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('spor', 'Spor'), ('yemek', 'Yemek'), ('oyun', 'Oyun'), ('teknoloji', 'Teknoloji'), ('film', 'Film/Dizi'), ('genel', 'Genel')], default='genel', max_length=20)),
                ('tarz', models.CharField(choices=[('kisa', 'Kısa'), ('adim_adim', 'Adım adım'), ('bol_ornek', 'Bol örnek'), ('hafif_mizah', 'Hafif mizah')], default='adim_adim', max_length=20)),
                ('seviye', models.CharField(choices=[('baslangic', 'Başlangıç'), ('orta', 'Orta'), ('ileri', 'İleri')], default='baslangic', max_length=20)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doc_tercih', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
