# Generated by Django 5.2.11 on 2026-03-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokuman', '0003_kullanicitercih'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anlamadimkaydi',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='anlamadimkaydi',
            name='dokuman_anl_kullani_35c897_idx',
        ),
        migrations.RemoveIndex(
            model_name='anlamadimkaydi',
            name='dokuman_anl_dokuman_3f2d70_idx',
        ),
        migrations.RemoveIndex(
            model_name='anlamadimkaydi',
            name='dokuman_anl_kaynak__3336d9_idx',
        ),
        migrations.RenameField(
            model_name='anlamadimkaydi',
            old_name='notlar',
            new_name='cikti_text',
        ),
        migrations.RenameField(
            model_name='anlamadimkaydi',
            old_name='cozum_notu',
            new_name='kullanici_mesaj',
        ),
        migrations.RemoveField(
            model_name='anlamadimkaydi',
            name='baslangic_char',
        ),
        migrations.RemoveField(
            model_name='anlamadimkaydi',
            name='bitis_char',
        ),
        migrations.RemoveField(
            model_name='anlamadimkaydi',
            name='cozulme_zamani',
        ),
        migrations.RemoveField(
            model_name='anlamadimkaydi',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='anlamadimkaydi',
            name='guncellendi',
        ),
        migrations.RemoveField(
            model_name='anlamadimkaydi',
            name='kaynak_id',
        ),
        migrations.RemoveField(
            model_name='anlamadimkaydi',
            name='kaynak_tipi',
        ),
        migrations.RemoveField(
            model_name='anlamadimkaydi',
            name='sayfa_no',
        ),
        migrations.RemoveField(
            model_name='anlamadimkaydi',
            name='secim_metni',
        ),
        migrations.AddField(
            model_name='anlamadimkaydi',
            name='adres',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anlamadimkaydi',
            name='cikti_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anlamadimkaydi',
            name='parca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anlamadim_kayitlari', to='dokuman.parca'),
        ),
        migrations.AddField(
            model_name='anlamadimkaydi',
            name='seviye',
            field=models.CharField(blank=True, default='baslangic', max_length=20),
        ),
        migrations.AddField(
            model_name='anlamadimkaydi',
            name='tarz',
            field=models.CharField(blank=True, default='adim_adim', max_length=20),
        ),
        migrations.AddField(
            model_name='anlamadimkaydi',
            name='tema',
            field=models.CharField(blank=True, default='genel', max_length=20),
        ),
    ]
