# Generated by Django 5.2.11 on 2026-03-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokuman', '0004_alter_anlamadimkaydi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicitercih',
            name='seviye',
            field=models.CharField(choices=[('baslangic', 'Başlangıç'), ('orta', 'Orta'), ('ileri', 'İleri')], default='baslangic', max_length=32),
        ),
        migrations.AlterField(
            model_name='kullanicitercih',
            name='tarz',
            field=models.CharField(choices=[('adim_adim', 'Adım adım'), ('ornekli', 'Örnekli'), ('kisa', 'Kısa'), ('derin', 'Derin')], default='adim_adim', max_length=32),
        ),
        migrations.AlterField(
            model_name='kullanicitercih',
            name='tema',
            field=models.CharField(choices=[('genel', 'Genel'), ('yazilim', 'Yazılım'), ('saglik', 'Sağlık'), ('matematik', 'Matematik')], default='genel', max_length=32),
        ),
    ]
