# Generated by Django 5.2.11 on 2026-03-07 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokuman', '0005_alter_kullanicitercih_seviye_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='not',
            options={'ordering': ['-pinned', '-updated_at']},
        ),
        migrations.RemoveField(
            model_name='not',
            name='metin',
        ),
        migrations.AddField(
            model_name='not',
            name='adres',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='not',
            name='baslik',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='not',
            name='dokuman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='dokuman.dokuman'),
        ),
        migrations.AddField(
            model_name='not',
            name='etiketler',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='not',
            name='icerik',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='not',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='not',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='not',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='not',
            name='parca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='dokuman.parca'),
        ),
        migrations.CreateModel(
            name='DokumanNotu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(blank=True, default='', max_length=160)),
                ('baslik', models.CharField(blank=True, default='', max_length=120)),
                ('icerik', models.TextField(default='')),
                ('etiketler', models.JSONField(blank=True, default=list)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dokuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_notlari', to='dokuman.dokuman')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_notlari', to='dokuman.parca')),
            ],
            options={
                'ordering': ['-pinned', '-updated_at'],
                'indexes': [models.Index(fields=['owner', 'dokuman'], name='dokuman_dok_owner_i_7619a8_idx'), models.Index(fields=['dokuman', 'parca'], name='dokuman_dok_dokuman_30cc89_idx'), models.Index(fields=['owner', 'updated_at'], name='dokuman_dok_owner_i_2723b2_idx')],
            },
        ),
    ]
