# Generated by Django 5.2.11 on 2026-03-08 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokuman', '0006_alter_not_options_remove_not_metin_not_adres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='not',
            name='icerik',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='not',
            name='parca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notlar', to='dokuman.parca'),
        ),
    ]
