# Generated by Django 5.2.11 on 2026-03-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokuman', '0007_alter_not_icerik_alter_not_parca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='not',
            old_name='icerik',
            new_name='metin',
        ),
        migrations.AlterField(
            model_name='not',
            name='dokuman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notlar', to='dokuman.dokuman'),
        ),
    ]
