# Generated by Django 5.2.11 on 2026-03-10 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokuman', '0009_not_dokuman_notnull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='not',
            options={},
        ),
        migrations.AlterField(
            model_name='not',
            name='adres',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='not',
            name='baslik',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='not',
            name='dokuman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='dokuman.dokuman'),
        ),
        migrations.AlterField(
            model_name='not',
            name='metin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='not',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='not',
            name='parca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='dokuman.parca'),
        ),
    ]
