# Generated by Django 5.2.11 on 2026-03-12 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokuman', '0010_alter_not_options_alter_not_adres_alter_not_baslik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='detay',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='mizah',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='ornek',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='sinav_modu',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='stil',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profil',
            name='unvan',
            field=models.CharField(blank=True, default='Yeni Başlayan', max_length=100),
        ),
        migrations.AddField(
            model_name='profil',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profil',
            name='seviye',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OdulLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaynak', models.CharField(default='boss', max_length=50)),
                ('puan', models.IntegerField(default=0)),
                ('xp_kazanilan', models.IntegerField(default=0)),
                ('aciklama', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dokuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokuman_odul_loglari', to='dokuman.dokuman')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokuman_odul_loglari', to=settings.AUTH_USER_MODEL)),
                ('parca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokuman_odul_loglari', to='dokuman.parca')),
            ],
        ),
    ]
