# Generated by Django 5.2.11 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokuman", "0011_remove_profil_detay_remove_profil_mizah_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YapayZekaModeli",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ad", models.CharField(max_length=120)),
                ("aciklama", models.TextField(blank=True)),
                ("gguf_dosya_adi", models.CharField(max_length=255)),
                ("gguf_dosya_yolu", models.CharField(max_length=500)),
                ("model_kisa_adi", models.CharField(default="qwen-docverse", max_length=120)),
                ("kuantizasyon_turu", models.CharField(default="Q4_K_M", max_length=50)),
                ("aktif_mi", models.BooleanField(default=True)),
                ("varsayilan_mi", models.BooleanField(default=False)),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncellenme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Yapay Zeka Modeli",
                "verbose_name_plural": "Yapay Zeka Modelleri",
            },
        ),
    ]
