# Generated by Codex for DocVerse productization groundwork.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokuman", "0012_yapayzekamodeli"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="not",
            options={"ordering": ["-pinned", "-updated_at", "-id"]},
        ),
        migrations.AddField(
            model_name="dokumannotu",
            name="arsivli",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dokumannotu",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dokumannotu",
            name="not_turu",
            field=models.CharField(
                choices=[("portal_calisma", "Portal Calisma"), ("portal_ozet", "Portal Ozet")],
                default="portal_calisma",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="dokumannotu",
            name="olusturma_kaynagi",
            field=models.CharField(
                choices=[("user", "User"), ("ai", "AI")],
                default="user",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="not",
            name="arsivli",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="not",
            name="kaynak_parca_idleri",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="not",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="not",
            name="not_turu",
            field=models.CharField(
                choices=[
                    ("serbest", "Serbest"),
                    ("ozet", "Ozet"),
                    ("kaynak", "Kaynak"),
                    ("calisma", "Calisma"),
                ],
                default="serbest",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="not",
            name="olusturma_kaynagi",
            field=models.CharField(
                choices=[("user", "User"), ("ai", "AI")],
                default="user",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="MetrikKaydi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ilgili_not_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ilgili_portal_not_id", models.PositiveIntegerField(blank=True, null=True)),
                ("olay_turu", models.CharField(max_length=64)),
                ("kaynak_modul", models.CharField(default="dokuman.api", max_length=64)),
                ("skor_ozeti", models.JSONField(blank=True, default=dict)),
                ("durum", models.CharField(default="ok", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dokuman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metrik_kayitlari",
                        to="dokuman.dokuman",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrik_kayitlari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metrik_kayitlari",
                        to="dokuman.parca",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["kullanici", "created_at"], name="dokuman_met_kullani_0aab03_idx"),
                    models.Index(fields=["olay_turu", "created_at"], name="dokuman_met_olay_t_89f31c_idx"),
                    models.Index(fields=["dokuman", "olay_turu"], name="dokuman_met_dokuman_2177f2_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="dokumannotu",
            name="bagli_notlar",
            field=models.ManyToManyField(blank=True, related_name="bagli_portal_notlar", to="dokuman.not"),
        ),
        migrations.AddField(
            model_name="dokumannotu",
            name="kaynak_parcalar",
            field=models.ManyToManyField(blank=True, related_name="bagli_portal_notlar", to="dokuman.parca"),
        ),
        migrations.AddIndex(
            model_name="not",
            index=models.Index(fields=["owner", "dokuman"], name="dokuman_not_owner_i_57d8a0_idx"),
        ),
        migrations.AddIndex(
            model_name="not",
            index=models.Index(fields=["owner", "parca"], name="dokuman_not_owner_i_0fe8bd_idx"),
        ),
        migrations.AddIndex(
            model_name="not",
            index=models.Index(fields=["owner", "updated_at"], name="dokuman_not_owner_i_64b632_idx"),
        ),
        migrations.AddIndex(
            model_name="not",
            index=models.Index(fields=["owner", "not_turu"], name="dokuman_not_owner_i_998269_idx"),
        ),
    ]
