# Generated by Codex for feedback and study/export groundwork.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokuman", "0013_notlar_portal_metrik_zemini"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="metrikkaydi",
            name="ilgili_feedback_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="KullaniciGeriBildirim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feedback_turu", models.CharField(choices=[("iyi", "Iyi"), ("kotu", "Kotu"), ("eksik", "Eksik"), ("alakasiz", "Alakasiz")], max_length=24)),
                ("kisa_not", models.CharField(blank=True, default="", max_length=280)),
                ("kaynak_modul", models.CharField(default="dokuman.api", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dokuman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geri_bildirimler",
                        to="dokuman.dokuman",
                    ),
                ),
                (
                    "not_kaydi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geri_bildirimler",
                        to="dokuman.not",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geri_bildirimler",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geri_bildirimler",
                        to="dokuman.parca",
                    ),
                ),
                (
                    "portal_not",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geri_bildirimler",
                        to="dokuman.dokumannotu",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "created_at"], name="dokuman_kul_owner_i_7ab942_idx"),
                    models.Index(fields=["feedback_turu", "created_at"], name="dokuman_kul_feedbac_95f770_idx"),
                    models.Index(fields=["kaynak_modul", "created_at"], name="dokuman_kul_kaynak__7af523_idx"),
                ],
            },
        ),
    ]
