# Generated by Codex for personalization support.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokuman", "0014_feedback_ve_metric_iliski"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kullanicitercih",
            name="tema",
            field=models.CharField(
                choices=[
                    ("genel", "Genel"),
                    ("yazilim", "Yazılım"),
                    ("saglik", "Sağlık"),
                    ("matematik", "Matematik"),
                    ("spor", "Spor"),
                    ("yemek", "Yemek"),
                    ("oyun", "Oyun"),
                    ("teknoloji", "Teknoloji"),
                    ("film", "Film"),
                ],
                default="genel",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="kullanicitercih",
            name="detay_seviyesi",
            field=models.CharField(
                choices=[("dusuk", "Düşük"), ("orta", "Orta"), ("yuksek", "Yüksek")],
                default="orta",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="kullanicitercih",
            name="mizah_seviyesi",
            field=models.CharField(
                choices=[("yok", "Yok"), ("hafif", "Hafif"), ("orta", "Orta")],
                default="yok",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="kullanicitercih",
            name="ton",
            field=models.CharField(
                choices=[("kanka", "Kanka"), ("hoca", "Hoca"), ("teknik", "Teknik"), ("sunum", "Sunum")],
                default="teknik",
                max_length=32,
            ),
        ),
    ]
