# Generated by Django 5.2.11 on 2026-03-01 01:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=60, unique=True)),
                ('ad', models.CharField(max_length=120)),
                ('aciklama', models.TextField(blank=True)),
                ('kosul_tur', models.CharField(choices=[('BOSS_TAMAMLAMA', 'Boss tamamla sayısı'), ('TOPLAM_XP', 'Toplam XP'), ('TOPLAM_PUAN', 'Toplam puan'), ('STREAK', 'Streak gün'), ('PERFECT', 'Perfect deneme')], max_length=30)),
                ('kosul_deger', models.PositiveIntegerField(default=1)),
                ('param', models.JSONField(blank=True, default=dict)),
                ('odul_xp', models.PositiveIntegerField(default=100)),
                ('odul_puan', models.PositiveIntegerField(default=50)),
                ('rozet', models.CharField(blank=True, default='', max_length=60)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BossKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Esya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=60, unique=True)),
                ('ad', models.CharField(max_length=120)),
                ('tip', models.CharField(choices=[('BOOSTER', 'Booster'), ('TITLE', 'Unvan'), ('SKIN', 'Skin')], max_length=20)),
                ('sure_dk', models.PositiveIntegerField(default=0)),
                ('xp_carpan', models.FloatField(default=1.0)),
                ('puan_carpan', models.FloatField(default=1.0)),
                ('fiyat_puan', models.PositiveIntegerField(default=0)),
                ('fiyat_xp', models.PositiveIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120)),
                ('tur', models.CharField(choices=[('DAILY', 'Günlük'), ('WEEKLY', 'Haftalık')], default='DAILY', max_length=10)),
                ('hedef_tur', models.CharField(choices=[('DENEME', 'Deneme yap'), ('BOSS_TAMAMLA', 'Boss tamamla'), ('PUAN_TOPLA', 'Puan topla'), ('XP_TOPLA', 'XP topla'), ('PERFECT', 'Mükemmel skor')], max_length=20)),
                ('hedef_deger', models.PositiveIntegerField(default=1)),
                ('param', models.JSONField(blank=True, default=dict)),
                ('odul_xp', models.PositiveIntegerField(default=50)),
                ('odul_puan', models.PositiveIntegerField(default=20)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('mesaj', models.TextField()),
                ('okundu', models.BooleanField(default=False)),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120)),
                ('aciklama', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('seviye_gereksinim', models.PositiveIntegerField(default=1)),
                ('siralama', models.PositiveIntegerField(default=1)),
                ('zorluk', models.PositiveIntegerField(default=1)),
                ('enerji_maliyeti', models.PositiveIntegerField(default=1)),
                ('cooldown_saniye', models.PositiveIntegerField(default=10)),
                ('odul_xp', models.PositiveIntegerField(default=100)),
                ('odul_puan', models.PositiveIntegerField(default=100)),
                ('tamamlama_esigi', models.PositiveIntegerField(default=60)),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bosslar', to='oyun.bosskategori')),
            ],
        ),
        migrations.CreateModel(
            name='BossSoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('MCQ', 'Çoktan Seçmeli'), ('TEXT', 'Metin')], default='MCQ', max_length=10)),
                ('soru_metni', models.TextField()),
                ('secenekler', models.JSONField(blank=True, default=list)),
                ('dogru_secenek_index', models.IntegerField(blank=True, null=True)),
                ('dogru_cevap_metni', models.CharField(blank=True, default='', max_length=500)),
                ('kabul_edilen_cevaplar', models.JSONField(blank=True, default=list)),
                ('max_puan', models.PositiveIntegerField(default=100)),
                ('boss', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soru', to='oyun.boss')),
            ],
        ),
        migrations.CreateModel(
            name='BossDeneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap_metni', models.TextField(blank=True, default='')),
                ('secilen_index', models.IntegerField(blank=True, null=True)),
                ('puan', models.PositiveIntegerField(default=0)),
                ('dogru_mu', models.BooleanField(default=False)),
                ('xp_eklendi', models.PositiveIntegerField(default=0)),
                ('puan_eklendi', models.PositiveIntegerField(default=0)),
                ('enerji_harcandi', models.PositiveIntegerField(default=0)),
                ('olusturuldu', models.DateTimeField(default=django.utils.timezone.now)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denemeler', to='oyun.boss')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_denemeleri', to=settings.AUTH_USER_MODEL)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denemeler', to='oyun.bosssoru')),
            ],
        ),
        migrations.CreateModel(
            name='AktifBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitis', models.DateTimeField()),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aktif_booster', to=settings.AUTH_USER_MODEL)),
                ('esya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktifler', to='oyun.esya')),
            ],
        ),
        migrations.CreateModel(
            name='OdulIslemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaynak', models.CharField(choices=[('BOSS', 'Boss'), ('GOREV', 'Görev'), ('BASARIM', 'Başarım'), ('MARKET', 'Market'), ('GIRIS', 'Günlük giriş')], max_length=20)),
                ('aciklama', models.CharField(blank=True, default='', max_length=255)),
                ('delta_xp', models.IntegerField(default=0)),
                ('delta_puan', models.IntegerField(default=0)),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odul_islemleri', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OyunProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_xp', models.PositiveIntegerField(default=0)),
                ('seviye', models.PositiveIntegerField(default=1)),
                ('toplam_puan', models.PositiveIntegerField(default=0)),
                ('enerji', models.PositiveIntegerField(default=10)),
                ('enerji_max', models.PositiveIntegerField(default=10)),
                ('enerji_son_yenileme', models.DateTimeField(default=django.utils.timezone.now)),
                ('enerji_yenileme_saniye', models.PositiveIntegerField(default=600)),
                ('streak_gun', models.PositiveIntegerField(default=0)),
                ('son_giris_tarihi', models.DateField(blank=True, null=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oyun_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BossIlerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_yuksek_puan', models.PositiveIntegerField(default=0)),
                ('xp_kazanilan_toplam', models.PositiveIntegerField(default=0)),
                ('puan_kazanilan_toplam', models.PositiveIntegerField(default=0)),
                ('tamamlandi', models.BooleanField(default=False)),
                ('deneme_sayisi', models.PositiveIntegerField(default=0)),
                ('son_deneme', models.DateTimeField(blank=True, null=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilerlemeler', to='oyun.boss')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_ilerlemeleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'boss')},
            },
        ),
        migrations.CreateModel(
            name='BossOnKosul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_kosullar', to='oyun.boss')),
                ('gerekir_boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kapi_acanlar', to='oyun.boss')),
            ],
            options={
                'unique_together': {('boss', 'gerekir_boss')},
            },
        ),
        migrations.CreateModel(
            name='Envanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=0)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envanter', to=settings.AUTH_USER_MODEL)),
                ('esya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envanterler', to='oyun.esya')),
            ],
            options={
                'unique_together': {('kullanici', 'esya')},
            },
        ),
        migrations.CreateModel(
            name='KullaniciBasarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kazanildi', models.DateTimeField(auto_now_add=True)),
                ('basarim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kazananlar', to='oyun.basarim')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basarimlarim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'basarim')},
            },
        ),
        migrations.CreateModel(
            name='KullaniciGorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.DateField()),
                ('bitis', models.DateField()),
                ('ilerleme', models.PositiveIntegerField(default=0)),
                ('tamamlandi', models.BooleanField(default=False)),
                ('odul_alindi', models.BooleanField(default=False)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanicilar', to='oyun.gorev')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevlerim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'gorev', 'baslangic', 'bitis')},
            },
        ),
    ]
