# Generated by Django 5.2.11 on 2026-03-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossdeneme',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
