# Generated by Django 5.2.11 on 2026-03-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyun', '0002_bossdeneme_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosssoru',
            name='ai_degerlendirme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bosssoru',
            name='context_doc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
