# Generated by Django 5.2.11 on 2026-03-03 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyun', '0003_bosssoru_ai_degerlendirme_bosssoru_context_doc_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='oyunprofil',
            old_name='enerji_son_yenileme',
            new_name='enerji_son_guncelleme',
        ),
        migrations.RemoveField(
            model_name='oyunprofil',
            name='enerji_max',
        ),
        migrations.RemoveField(
            model_name='oyunprofil',
            name='enerji_yenileme_saniye',
        ),
        migrations.RemoveField(
            model_name='oyunprofil',
            name='guncellendi',
        ),
        migrations.RemoveField(
            model_name='oyunprofil',
            name='seviye',
        ),
        migrations.RemoveField(
            model_name='oyunprofil',
            name='son_giris_tarihi',
        ),
        migrations.RemoveField(
            model_name='oyunprofil',
            name='streak_gun',
        ),
        migrations.AlterField(
            model_name='oyunprofil',
            name='enerji',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='oyunprofil',
            name='toplam_puan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oyunprofil',
            name='toplam_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GorevIlerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilerleme_sayi', models.IntegerField(default=0)),
                ('tamamlandi', models.BooleanField(default=False)),
                ('odul_alindi', models.BooleanField(default=False)),
                ('xp_kazanilan_toplam', models.IntegerField(default=0)),
                ('puan_kazanilan_toplam', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilerlemeler', to='oyun.gorev')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorev_ilerlemeler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'gorev')},
            },
        ),
        migrations.CreateModel(
            name='OdulLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('xp_delta', models.IntegerField(default=0)),
                ('puan_delta', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odul_loglari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='KullaniciGorev',
        ),
        migrations.CreateModel(
            name='KullaniciGorev',
            fields=[
            ],
            options={
                'verbose_name': 'Kullanıcı Görev',
                'verbose_name_plural': 'Kullanıcı Görevler',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oyun.gorevilerleme',),
        ),
    ]
