# Generated by Django 5.2.11 on 2026-03-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyun', '0004_rename_enerji_son_yenileme_oyunprofil_enerji_son_guncelleme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oyunprofil',
            name='enerji_max',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='oyunprofil',
            name='enerji_yenileme_saniye',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='oyunprofil',
            name='guncellendi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oyunprofil',
            name='seviye',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='oyunprofil',
            name='son_giris_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oyunprofil',
            name='streak_gun',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oyunprofil',
            name='enerji',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='oyunprofil',
            name='toplam_puan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oyunprofil',
            name='toplam_xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
