# Generated by Django 5.2.11 on 2026-03-03 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyun', '0005_oyunprofil_enerji_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='KullaniciGorev',
        ),
        migrations.CreateModel(
            name='KullaniciGorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.DateField()),
                ('bitis', models.DateField()),
                ('ilerleme', models.PositiveIntegerField(default=0)),
                ('tamamlandi', models.BooleanField(default=False)),
                ('odul_alindi', models.BooleanField(default=False)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanicilar', to='oyun.gorev')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevlerim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'gorev', 'baslangic', 'bitis')},
            },
        ),
    ]
